version: '3.8'

services:
    mysql:
        image: mysql:latest
        container_name: mysql_deckbuilder
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: deckbuilderyugioh
        ports:
          - "3306:3306"
        volumes:
          - ./mysql_data:/var/lib/mysql
    
    redis:
        image: redis/redis-stack:latest
        container_name: redis_deckbuilder
        ports:
          - "6379:6379"
          - "8001:8001"
    
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq_deckbuilder
        ports:
          - "5672:5672"
          - "15672:15672"

volumes:
  mysql_data: